spring:
  jpa:
    show-sql: false
  data:
    redis:
      timeout: 5000ms

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    com.vietjourney: INFO
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
